"""add residence to user

Revision ID: 4bbe8e6f8a71
Revises: f6b62d700ca1
Create Date: 2026-07-07 14:31:08.444456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbe8e6f8a71'
down_revision: Union[str, Sequence[str], None] = 'f6b62d700ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Residence', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['Residence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'Residence')
    # ### end Alembic commands ###
