"""rename Residence to residence

Revision ID: 64aab5129109
Revises: 4bbe8e6f8a71
Create Date: 2026-07-07 15:24:35.451540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64aab5129109'
down_revision: Union[str, Sequence[str], None] = '4bbe8e6f8a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('residence', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_Residence_key'), 'users', type_='unique')
    op.drop_column('users', 'Residence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Residence', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_Residence_key'), 'users', ['Residence'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'residence')
    # ### end Alembic commands ###
