"""rename Residence to residence

Revision ID: 64aab5129109
Revises: 4bbe8e6f8a71
Create Date: 2026-07-07 15:24:35.451540

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64aab5129109'
down_revision: Union[str, Sequence[str], None] = '4bbe8e6f8a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "Residence",
        new_column_name="residence"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "residence",
        new_column_name="Residence"
    )
    # ### end Alembic commands ###
